---
- name: Manage web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Stop Apache
      service:
        name: apache2
        state: stopped

    - name: Remove Apache
      apt:
        name: apache2
        state: absent

    - name: Remove index.html
      file:
        path: /var/www/html/index.html
        state: absent
